### PR TITLE
fix class loading with python 3

### PR DESCRIPTION
**Pull request by syphar**

### CODE REVIEW

**Comment by syphar** [comment]
@codingjoe test failures don't seem related to my change

**Comment by syphar** [comment]
@codingjoe manual test is fine on python3

**Comment by codingjoe** [comment]
@syphar second time you touch that line, please provide a unit test

**Comment by syphar** [comment]
@codingjoe 
- fixed pytest-django 
- did the actual bugfix and added tests for deconstruct / construct, and for the backwards-compatible case
- set some build to allow-fail
- killed `runtests.py` (we can discuss this, but `runtests.py` is a frozen `py.test` executable, which broke because it was quite old. To me it feels better when `pip install pytest` leads to an up-to-date py.test version, and not the old `runtests.py` frozen version is used.

**Comment by codingjoe** [comment]
@syphar can you split that into to PRs, first fixing the tests and your bug

**Comment by syphar** [comment]
@codingjoe which ones? 
every commit into a separate PR?

**Comment by coddingtonbear** [comment]
Oh, I think @codingjoe is just requesting that the changes fixing this bug should perhaps be in a PR separated from the changes to the testing and travis infrastructure.

**Comment by syphar** [comment]
@codingjoe separated the PR, see #14 

tests for this PR will fail on PR because of the missing updated matrix, and the  outdated, frozen `runtests.py`

**Comment by codingjoe** [comment]
@syphar thanks, please rebase on current master, I changed the test setup a bit more.

@coddingtonbear side note: @syphar is sitting to my left :wink:

**Comment by syphar** [comment]
@codingjoe rebased, fixed the conflicts and the flake errors

**Comment by codingjoe** [comment]
released in 2.0.2

**Pull request closed without merging**
